baseURL = 'https://www.svt.se/'
languageCode = "sv"
defaultContentLanguageInSubdir = false
defaultContentLanguage = "sv"
theme = "open"
sectionPagesMenu = "main"
relativeURLs = true

[languages]
  [languages.sv]
    title = 'SVT Open'
    languageName = "Svenska"
    contentDir="content/sv"
    weight = 1
  [[languages.sv.menu.footer]]
    name = "Om SVT"
    url = "https://omoss.svt.se"
  [languages.en]
    title = 'SVT Open'
    languageName = "English"
    contentDir="content/en"
    weight = 2
  [[languages.en.menu.footer]]
    name = "About SVT"
    url = "https://omoss.svt.se/about-svt.html"

[params]
  url = 'https://www.svt.se/open/'
  images = ['/img/waterfall.webp']

